version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883" # This needs to be deleted in deployment
      - "8883:8883"

    expose:
      - "1883" # For docker internal network only
      - "8883"
    
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs:/mosquitto/certs
    
    networks:
      - measurement-system
  
  
  postgres:
    image: postgres:15
    restart: unless-stopped

    # Load environment variables from general .env file
    env_file:
      - .env

    # Expose port 5432 for internal access only
    expose:
      - "5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - measurement-system


  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - measurement-system


  python_logger:
    image: python_logger
    restart: unless-stopped

    depends_on:
      - postgres
      - mosquitto

    env_file:
      - .env

    build: 
      dockerfile: Dockerfile
      context: ./python_files

    command: 
      python3 main.py

    networks:
      - measurement-system  
  
    

volumes:
  mosquitto:
  postgres_data:
  grafana_storage:

networks:
  measurement-system:
    driver: bridge